server:
  address: 13.124.90.163
  port: 8080
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: github-trendu

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true