name: github-trendu dev CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      #.env 파일 생성
      - name: Setting .env
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      # JDK 설치
      - name: Set up JDK 22
        uses: actions/setup-java@v1
        with:
          java-version: 22

      # 빌드 캐싱
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Gradle Build
      - name: Build with Gradle
        run: ./gradlew build

      # DockerHub 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # DockerHub Push
      - name: Build and Push Docker image
        run: |
          docker build -f Dockerfile-dev -t ${{ secrets.DOCKER_HUB_USERNAME }}/github-trendu-dev .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/github-trendu-dev
  

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # AWS 배포
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd github-trendu
            sudo docker stop github-trendu-dev
            sudo docker rm github-trendu-dev
            sudo docker run -it -d -p 8080:8080 --name github-trendu-dev gbtwld/github-trendu-dev